class tags():
    primareWindow = "w_primare"
    coordWindow = "w_coord"
    editWindow = "w_editCoord"
    inpNome = "inp_t_nome"
    inpCordX = "inp_d_cordX"
    inpCordZ = "inp_d_cordZ"

class labels():
    cords = "Coordenadas"
    config = "Configuração"
    editCord = "Edit. Coord"
    tb_col_nome = "Nome"
    tb_col_overWord = "OverWord"
    tb_col_nether = "Nether"
    save = "Save"
    novo = "Novo"
    editar = "Editar"
    trocar = "Trocar"
    btn_adicionar = "Adicionar"