class tags():
    primareWindow = "w_primare"
    coordWindow = "w_coord"
    editWindow = "w_editCoord"
    saveWindow = "w_save"
    novoSave = "w_novoSave"
    inpNome = "inp_t_nome"
    inpCordX = "inp_d_cordX"
    inpCordZ = "inp_d_cordZ"
    attNome = "att_t_nome"
    attCordX = "att_d_cordX"
    attCordZ = "att_d_cordZ"
    valorAntigo = "att_valor_antigo"
    save = "sel_save"
    novoSaveNome = "inp_t_nomeNovoSave"

class labels():
    cords = "Coordenadas"
    config = "Configuração"
    editCord = "Edit. Coord"
    tb_col_nome = "Nome"
    tb_col_overWord = "OverWord"
    tb_col_nether = "Nether"
    save = "Save"
    novo = "Novo"
    editar = "Editar"
    trocar = "Trocar"
    btn_adicionar = "Adicionar"
    btn_atualizar = "Atualizar"
    novoSave = "Novo Save"
    cancelar = "Cancelar"